show test report in GitHub Action

diff --git a/.github/workflows/dotnet-console.yml b/.github/workflows/dotnet-console.yml
--- a/.github/workflows/dotnet-console.yml
+++ b/.github/workflows/dotnet-console.yml
@@ -25,4 +25,13 @@ jobs:
       run: dotnet build --no-restore
       
     - name: Test
-      run: dotnet test --no-build --verbosity normal
+      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
+      
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: .NET Test Results
+        path: "**/TestResults/*.trx"
+        reporter: dotnet-trx
+        fail-on-error: true
